apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: karpenter
spec:
  endpoints:
  - path: /metrics
    port: http-metrics
  namespaceSelector:
    matchNames:
    - karpenter
  selector:
    matchLabels:
      app.kubernetes.io/instance: karpenter
      app.kubernetes.io/name: karpenter
