apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - prometheus-rule-sqs.yaml

configMapGenerator:
- files:
  - aws-sqs.json
  - cw-logs.json

  name: grafana-dashboards-aws
  options:
    disableNameSuffixHash: true
    annotations:
      grafana-sidecar-target-folder: AWS
    labels:
      grafana_dashboard: 'true'
