apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../base

configMapGenerator:
  - name: aws-ebs-csi-driver-values
    namespace: kube-system
    files:
      - values.yaml=aws-ebs-csi-driver-values.yaml

  - name: aws-load-balancer-controller-values
    namespace: kube-system
    files:
      - values.yaml=aws-load-balancer-controller-values.yaml

  - name: aws-vpc-cni-values
    namespace: kube-system
    files:
      - values.yaml=aws-vpc-cni-values.yaml

  - name: cert-manager-values
    namespace: kube-system
    files:
      - values.yaml=cert-manager-values.yaml

  - name: external-dns-values
    namespace: kube-system
    files:
      - values.yaml=external-dns-values.yaml

configurations:
  - kustomizeconfig.yaml
