apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonAnnotations:
  grafana-sidecar-target-folder: Prometheus-Operator

commonLabels:
  grafana_dashboard: 'true'

resources:
- dashboards.yaml
