---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: monitoring-extra
spec:
  interval: 15m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./infrastructure/monitoring-extra/prod
  prune: true
  decryption:
    provider: sops
  dependsOn:
    - name: monitoring
