apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: grafana
  namespace: monitoring
spec:
  releaseName: grafana
  chart:
    spec:
      chart: grafana
      version: '6.56.5'
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: flux-system
  interval: 15m
  install:
    crds: CreateReplace
  upgrade:
    crds: CreateReplace
  valuesFrom:
    - kind: ConfigMap
      name: grafana-values
    - kind: Secret
      name: grafana-secrets
  dependsOn:
    - name: loki
    - name: kube-prometheus-stack
