apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kube-prometheus-stack
  namespace: monitoring
spec:
  releaseName: kube-prometheus-stack
  chart:
    spec:
      chart: kube-prometheus-stack
      version: '45.29.0'
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: flux-system
  interval: 15m
  install:
    crds: CreateReplace
  upgrade:
    crds: CreateReplace
  valuesFrom:
    - kind: ConfigMap
      name: kube-prometheus-stack-values
    - kind: Secret
      name: kube-prometheus-stack-secrets
  dependsOn:
    - name: metrics-server
      namespace: kube-system
    - name: ingress-nginx-private
      namespace: ingress-nginx-private
