---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: aws-vpc-cni
  namespace: kube-system
spec:
  releaseName: aws-vpc-cni
  chart:
    spec:
      chart: aws-vpc-cni
      version: '1.2.8'
      sourceRef:
        kind: HelmRepository
        name: eks
        namespace: flux-system
  interval: 15m
  install:
    crds: CreateReplace
  upgrade:
    crds: CreateReplace
  valuesFrom:
    - kind: ConfigMap
      name: aws-vpc-cni-values
