apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cert-manager
  namespace: kube-system
spec:
  releaseName: cert-manager
  chart:
    spec:
      chart: cert-manager
      version: 'v1.12.0'
      sourceRef:
        kind: HelmRepository
        name: jetstack
        namespace: flux-system
  interval: 15m
  install:
    crds: CreateReplace
  upgrade:
    crds: CreateReplace
  valuesFrom:
    - kind: ConfigMap
      name: cert-manager-values
