apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: external-dns
  namespace: kube-system
spec:
  releaseName: external-dns
  chart:
    spec:
      chart: external-dns
      version: '1.12.2'
      sourceRef:
        kind: HelmRepository
        name: external-dns
        namespace: flux-system
  interval: 15m
  install:
    crds: CreateReplace
  upgrade:
    crds: CreateReplace
  valuesFrom:
    - kind: ConfigMap
      name: external-dns-values
