apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: metrics-server
  namespace: kube-system
spec:
  releaseName: metrics-server
  chart:
    spec:
      chart: metrics-server
      version: '3.10.0'
      sourceRef:
        kind: HelmRepository
        name: metrics-server
        namespace: flux-system
  interval: 15m
  install:
    crds: CreateReplace
  upgrade:
    crds: CreateReplace

  values:
    replicas: 2
    args:
      - --metric-resolution=15s
      - --kubelet-insecure-tls=true

