apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: aws-ebs-csi-driver
  namespace: flux-system
spec:
  url: https://kubernetes-sigs.github.io/aws-ebs-csi-driver
  interval: 1h
