apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- gotk-components.yaml
- gotk-sync.yaml

patches:
- patch: |-
    - op: add
      path: /metadata/annotations/eks.amazonaws.com~1role-arn
      value: arn:aws:iam::PLACEHOLDER:role/PLACEHOLDER
  target:
    kind: ServiceAccount
    name: ^(image-reflector|kustomize)-controller$
- patch: |-
    - op: add
      path: /spec/decryption
      value:
        provider: sops
  target:
    kind: Kustomization
    name: flux-system
