apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../base

configMapGenerator:
  - name: weave-gitops-values
    namespace: flux-system
    files:
      - values.yaml=weave-gitops-values.yaml

configurations:
  - kustomizeconfig.yaml
