---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: karpenter-provisioner
spec:
  interval: 15m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./infrastructure/karpenter-provisioner/stage
  prune: true
  decryption:
    provider: sops
  dependsOn:
    - name: system
    - name: karpenter
