apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: monitoring
spec:
  interval: 15m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./infrastructure/monitoring/stage
  prune: true
  decryption:
    provider: sops
  dependsOn:
    - name: ingress
