apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../base

components:
  - ../base/yace

configMapGenerator:
  - name: grafana-values
    namespace: monitoring
    files:
      - values.yaml=grafana-values.yaml
  - name: kube-prometheus-stack-values
    namespace: monitoring
    files:
      - values.yaml=kube-prometheus-stack-values.yaml
  - name: loki-values
    namespace: monitoring
    files:
      - values.yaml=loki-values.yaml
  - name: promtail-values
    namespace: monitoring
    files:
      - values.yaml=promtail-values.yaml
  - name: yace-values
    namespace: monitoring
    files:
      - values.yaml=yace-values.yaml

secretGenerator:
  - name: grafana-secrets
    namespace: monitoring
    files:
      - values.yaml=grafana-secrets.yaml
  - name: kube-prometheus-stack-secrets
    namespace: monitoring
    files:
      - values.yaml=kube-prometheus-stack-secrets.yaml

configurations:
  - kustomizeconfig.yaml
