apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- podmonitor.yaml
- prometheus-rule.yaml

configMapGenerator:
- files:
  - cluster.json
  - control-plane.json
  - logs.json
  name: grafana-dashboards-flux
  namespace: monitoring
  options:
    disableNameSuffixHash: true
    annotations:
      grafana-sidecar-target-folder: Flux
    labels:
      grafana_dashboard: 'true'
