apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: fluxcd
  namespace: flux-system
  labels:
    app.kubernetes.io/part-of: flux
spec:
  groups:
  - name: GitOpsToolkit
    rules:
    - alert: ReconciliationFailure
      annotations:
        summary: '{{ $labels.kind }} {{ $labels.exported_namespace }}/{{ $labels.name
          }} reconciliation has been failing for more than ten minutes.'
      expr: max(gotk_reconcile_condition{status="False",type="Ready"}) by (exported_namespace,
        name, kind) + on(exported_namespace, name, kind) (max(gotk_reconcile_condition{status="Deleted"})
        by (exported_namespace, name, kind)) * 2 == 1
      for: 10m
      labels:
        severity: page
