serviceAccount:
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::PLACEHOLDER:role/PLACEHOLDER

test:
  enabled: false

monitoring:
  selfMonitoring:
    enabled: false
    grafanaAgent:
      installOperator: false
  lokiCanary:
    enabled: false
  dashboards:
    labels:
      grafana_dashboard: 'true'
    annotations:
      grafana-sidecar-target-folder: Loki

read:
  replicas: 3
  legacyReadTarget: false
  resources:
    requests:
      cpu: "1"
      memory: 2Gi

backend:
  replicas: 3

write:
  replicas: 3

gateway:
  replicas: 2

loki:
  auth_enabled: false
  commonConfig:
    replication_factor: 3
  server:
    http_server_read_timeout: 600s
    http_server_write_timeout: 600s
  querier:
    max_concurrent: 4096
  query_scheduler:
    max_outstanding_requests_per_tenant: 10000
  query_range:
    cache_results: true
  limits_config:
    split_queries_by_interval: 24h
  storage:
    type: s3
    bucketNames:
      chunks: PLACEHOLDER
      ruler: PLACEHOLDER
      admin: PLACEHOLDER
    s3:
      region: PLACEHOLDER
  schemaConfig:
    configs:
    - from: 2022-11-22
      store: boltdb-shipper
      object_store: s3
      schema: v12
      index:
        prefix: loki_index_
        period: 24h
