---
apiVersion: karpenter.sh/v1alpha5
kind: Provisioner
metadata:
  name: app-arm
spec:
  requirements:
    - key: kubernetes.io/arch
      operator: In
      values: [arm64]
    - key: karpenter.sh/capacity-type
      operator: In
      values: [on-demand, spot]
    - key: karpenter.k8s.aws/instance-family
      operator: In
      values: [t4g, m6g, c6g, r6g]
    - key: karpenter.k8s.aws/instance-size
      operator: NotIn
      values: [nano, micro, small]
  labels:
    kube/nodetype: app-arm
  taints:
    - key: dedicated
      value: app-arm
      effect: NoSchedule
  limits:
    resources:
      cpu: "100"
      memory: 100Gi
  providerRef:
    name: default
  consolidation:
    enabled: true
  kubeletConfiguration:
    maxPods: 110
