apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: weave-gitops
  namespace: flux-system
spec:
  chart:
    spec:
      chart: weave-gitops
      version: '4.0.21'
      sourceRef:
        kind: HelmRepository
        name: weave-gitops
  interval: 1h
  valuesFrom:
    - kind: ConfigMap
      name: weave-gitops-values
