---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ingress-nginx-private
  namespace: ingress-nginx-private
spec:
  releaseName: ingress-nginx-private
  targetNamespace: ingress-nginx-private
  storageNamespace: ingress-nginx-private
  chart:
    spec:
      chart: ingress-nginx
      version: '4.6.1'
      sourceRef:
        kind: HelmRepository
        name: ingress-nginx
        namespace: flux-system
  interval: 15m
  install:
    crds: CreateReplace
  upgrade:
    crds: CreateReplace
  valuesFrom:
    - kind: ConfigMap
      name: ingress-nginx-private-values
