apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../base

configMapGenerator:
  - name: karpenter-values
    namespace: karpenter
    files:
      - values.yaml=karpenter-values.yaml

configurations:
  - kustomizeconfig.yaml

patches:
- patch: |-
    - op: replace
      path: /spec/chart/spec/version
      value: v0.27.3
  target:
    kind: HelmRelease
